name: Chrome

on: [push, workflow_dispatch]

jobs:
  chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Chrome
        uses: cypress-io/github-action@v6
        timeout-minutes: 20
        with:
          build: npm run build
          start: npm start
          browser: chrome
      -run: npm run code-challenge
